services:
  migrate.reverb:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db.reverb
    volumes:
      - reverb:/home/oabta
    networks:
      reverb:
    env_file:
      - .env
    command: bash -c "./script/wait-for-it db.reverb:5432 && yes Y | php artisan migrate --force"

  reverb:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db.reverb
    volumes:
      - reverb:/home/oabta
    networks:
      reverb:
    env_file:
      - .env
    command: bash -c "./script/wait-for-it db.reverb:5432 && php artisan  reverb:start"

  db.reverb:
    image: "postgres:alpine"
    restart: unless-stopped
    expose:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db.reverb:/var/lib/postgresql/data
    networks:
      reverb:

networks:
  reverb:
volumes:
  db.reverb:
  reverb:
